spring.application.name=podvezi

# ??????????? ? ???? ??????
spring.datasource.url=jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.pjhbescryttitwjqncwg
spring.datasource.password=Y3B#bpagN9b7tJP
spring.datasource.user-class-name=org.postgresql.Driver

# ????????? Hibernate
 spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
 spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Flyway ????????? (???????????)
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-migration-naming=true


spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.check-template-location=false

